name: Build & Test

on:
  push:
  pull_request:   
    branches: [ main ]
  workflow_dispatch: 
permissions: 
  contents: read
  pages: write

jobs:
  build:
  runs-on: ubuntu-lates
  steps:
    -  uses: actions/chechkout@v4
    -  name: Build source code
       run: |
         ./scripts/build.sh
        timeout-minutes: 1
